spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/smart_campus_db
    username: postgres
    password: Thinuri@2002
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 273377619404-djl566ao3m823870eh242kfjb6r70m4v.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email

  sql:
    init:
      mode: never

server:
  port: 8080

file:
  upload-dir: uploads

