spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/smart_campus_db
    username: postgres
    password: Thinuri@2002
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test-client-id
            client-secret: test-client-secret
            scope: email,profile