spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/smart_campus_db
    username: postgres
    password: Thinuri@2002
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

server:
  port: 8080

file:
  upload-dir: uploads